// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]              = SECRET_SSID; // Network SSID (name)
const char PASS[]              = SECRET_OPTIONAL_PASS; // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]        = SECRET_DEVICE_KEY; // Secret device password

// --- Edited
const char DEVICE_LOGIN_NAME[] = SECRET_DEVICE_LOGIN_NAME; // Secret device login name
// --- End of Edited

void onVTextChange();
void onVColourChange();
void onVStopChange();

String vText;
float vHumidity;
float vTemperature;
CloudColoredLight vColour;
bool vStop;

void initProperties()
{
    ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
    ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
    ArduinoCloud.addProperty(vText, READWRITE, ON_CHANGE, onVTextChange);
    ArduinoCloud.addProperty(vHumidity, READ, ON_CHANGE, NULL);
    ArduinoCloud.addProperty(vTemperature, READ, ON_CHANGE, NULL);
    ArduinoCloud.addProperty(vColour, READWRITE, ON_CHANGE, onVColourChange);
    ArduinoCloud.addProperty(vStop, READWRITE, ON_CHANGE, onVStopChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
